# fly.toml app configuration file generated for building3d on 2026-07-08T20:44:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'building3d'
primary_region = 'ams'

[build]

[[mounts]]
  source = 'building3d_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
